### ISSUE TITLE
How to work well with node@4.2.6 and npm@2.14.12 ?

### ISSUE THREAD

**Issue by sunzongzheng** [babel/babel#6937]
### Input Code

```js
import 'babel-polyfill'
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    [
      "env",
      {
        "targets": {
          "node": "4.2.6"
        },
        "useBuiltIns": "usage"
      }
    ]
  ],
  "plugins": [
    [
      "transform-object-rest-spread",
      "transform-runtime"
    ]
  ]
}
```

### Expected Behavior

work well 

### Current Behavior

````bash
Cannot find module 'core-js/modules/es6.typed.array-buffer'
````

### Possible Solution

Perhaps the reasion is ,the dependencies aren't flatting like this
![image](https://user-images.githubusercontent.com/12635613/33424834-eef1a09a-d5f7-11e7-854a-2a819f28f098.png)

### Context
How can I use with node@4.2.6 and npm@2.14.12 ? 
I can't upgrade my version, sorry...

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0
| Babylon          | 
| node             | 4.2.6
| npm              | 2.14.12
| Operating System | Mac

**Comment by nicolo-ribaudo** [comment]
Can you try to `npm install --save core-js`?

**Comment by sunzongzheng** [comment]
@nicolo-ribaudo It could be resolved by that, but I want to know the perfect means. Because other dependencies have this problems too.
thx for response

**Comment by nicolo-ribaudo** [comment]
Babel expectes `core-js` to be hoisted by npm to the root `node_modules` folder. npm does that by default since npm@3, but you need to run `npm dedupe` if you are using npm@2 (I didn't know about that command when I first replied :smile:)

I agree that it should work by default with npm@2 without needing to run `npm dedupe`, since it is marked as supported https://github.com/babel/babel/blob/0a2a37c31f004e37611008287807fa584bac30f9/package.json#L66
