### ISSUE TITLE
Compilation error with preset-react: _helperPluginUtils.declare is not a function

### ISSUE THREAD

**Issue by jonkoops** [babel/babel#11786]
## Bug Report

**Current behavior**
Application does not compile with `@babel/preset-react@7.10.4`, using version `7.10.1` does.

**Input Code**
https://github.com/Amsterdam/atlas/tree/babel-bugreport 

Run `npm run start` on this branch.

**Expected behavior**
Code compiles as before

**Environment** 
```
  System:
    OS: Linux 5.6 Fedora 32 (Workstation Edition) 32 (Workstation Edition)
  Binaries:
    Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v14.5.0/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
  npmPackages:
    @babel/core: ^7.10.4 => 7.10.4 
    @babel/plugin-transform-runtime: ^7.10.4 => 7.10.4 
    @babel/preset-env: ^7.10.4 => 7.10.4 
    @babel/preset-react: ^7.10.1 => 7.10.1 
    @babel/preset-typescript: ^7.10.4 => 7.10.4 
    @babel/runtime: ^7.10.4 => 7.10.4 
    babel-eslint: ^10.1.0 => 10.1.0 
    babel-loader: ^8.1.0 => 8.1.0 
    babel-plugin-styled-components: ^1.10.7 => 1.10.7 
    babel-plugin-transform-commonjs-es2015-modules: ^4.0.1 => 4.0.1 
    eslint: ^7.3.1 => 7.3.1 
    jest: 26.1.0 => 26.1.0 
    karma-babel-preprocessor: 8.0.1 => 8.0.1 
    webpack: 4.43.0 => 4.43.0 

```

**Additional context**
![image](https://user-images.githubusercontent.com/695720/86457020-4e193000-bd23-11ea-81aa-adfbbab6a8e5.png)

**Comment by existentialism** [comment]
@jonkoops Thanks for the issue report!

First clue is the path:

`node_modules/@babel/preset-react/node_modules/@babel/plugin-transform-parameters`

Note the nesting?

Then, confirming by taking a look at your lockfile, there are a bunch of duplicated @babel/-related deps.

The "easiest" fix is to just remove all the `@babel/*` entries from the lock file and rerun `npm i`, which fixes things:

https://github.com/existentialism/atlas/commit/5918640580af4dc89f2fb095b6520c56caf94dd7

**Comment by jonkoops** [comment]
Thanks a lot @existentialism, that seems to resolve the issue :tada: Should probably have tried throwing away my lockfile first.

**Comment by existentialism** [comment]
@jonkoops glad it worked! I wouldn't recommend blowing away your lockfile, but there may be times when the package managers get super confused when updating just some parts of babel due to the sheer number of packages.
