### ISSUE TITLE
Cannot find module '@babel/plugin-syntax-dynamic-import' after upgrading babel from 7.4 to 7.5

### ISSUE THREAD

**Issue by endiliey** [babel/babel#10212]
## Bug Report

When upgrading babel from 7.4 to 7.5, babel broke

**Reproduction**
https://github.com/facebook/docusaurus/tree/endiliey/babel-upgrade

```bash
yarn
yarn start
```

**Expected behavior/code**

No error

**Actual behavior/code**
<img width="634" alt="babel-error" src="https://user-images.githubusercontent.com/17883920/61170570-333f3000-a595-11e9-8b9d-444fc246f053.PNG">

**Babel Configuration (.babelrc, package.json, cli command)**

our babel-loader is defined here
https://github.com/facebook/docusaurus/blob/871378766d30d06b5fdea7cf1d3546d62d9a7251/packages/docusaurus/src/webpack/utils.ts#L66-L81

**Environment**
- Babel version(s): 7.5.4
OS: Linux 4.4 Ubuntu 16.04.4 LTS (Xenial Xerus)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 12.2.0 - /tmp/yarn--1563015213319-0.6713813992237541/node
    Yarn: 1.12.3 - /tmp/yarn--1563015213319-0.6713813992237541/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.2.0/bin/npm
- Monorepo: lerna
- How you are using Babel: babel-loader

**Comment by nicolo-ribaudo** [comment]
Does that plugin exist in `node_modules`?

**Comment by endiliey** [comment]
@nicolo-ribaudo yes definitely. The only change in https://github.com/facebook/docusaurus/commit/871378766d30d06b5fdea7cf1d3546d62d9a7251 is bumping babel from 7.4 to 7.5

**Comment by JLHwung** [comment]
The problem comes from how yarn workspaces hoists dependencies.

Note that even if `@docusaurus/core` is symlinked to `docusaurus-2-website`, roughly speaking, every `require()` call in `@docusaurus/core` will be resolved in `docusaurus-2-website` context. (The reason is that `NODE_MODULE_PATHS` would _not_ follow the symlink, see [Node.js Module Resolution](https://nodejs.org/api/modules.html#modules_all_together)). Therefore
```js
// in docusaurus-2-website
require.resolve("@babel/core")
// returns PATH_TO_docusaurus/node_modules/@babel/core/lib/index.js
```

Yarn workspace will hoist the dependencies to the root node_modules if possible. When `babel` in `@docusaurus/core` is bumped from 7.4 to 7.5, for some reason I don't know, `@babel/plugin-syntax-dynamic-import` is _not_ hoisted to the root node_modules. Therefore `docusaurus-2-website` could not resolve this module.

I would suggest also update the `@babel/core` in the root `package.json` to see if `yarn workspace` would hoist `@babel/plugin-syntax-dynamic-import` again to the root node_modules.

**Comment by endiliey** [comment]
@JLHwung wohoo thanks a lot. seems to be some hoisting problem indeed.
