### ISSUE TITLE
require(...).default is not a function - make bootstrap - Babel Setup

### ISSUE THREAD

**Issue by pudility** [babel/babel#6143]
### Bug report

I am trying to compile babel using make and following the [setup](https://github.com/babel/babel/blob/master/CONTRIBUTING.md#setup) section in the docs. I ran across some dependency that where missing (See "Dependency error" at the bottom):

 - `pump`
 - `gulp-rename` 
 - `webpack-dependency-suite`
 - `enhanced-resolve`

 I added the missing dependency to the `package.json` (I am not sure if I was supposed to do this), and continued on with `make bootstrap` however I got the following error below. I am wondering what I should do differently so that I don't get this error. 

### Babel Configuration (.babelrc)

```js
{
 "presets": ["env"]
}
```

### Expected Behavior

It should have not given me an error. More specifically, (I think) it should have run `clean-all`, then installed and compiled the dependencies.

### Current Behavior

It gives me the below error.

### Context

I am trying to build babel. It affected me by not letting me build babel.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            | 6.26.0 (babel-core 6.26.0)
| node             | 7.10.0
| npm              | 4.2.0
| Operating System | OSX

I thought that the error might be caused because I am running npm 4.2.0 instead of npm 3, but I am not sure. It would be great if the documentation could be a little more specific about this:

> Make sure you are on npm 3

### Error:
```
[12:29:39] Compiling 'babel-core/src/config/loading/files/plugins.js'...
[12:29:39] Error: Multiple configuration files found. Please remove one:
- .babelrc
- .babelrc.js
from /Users/zoe/Developer/babel
    at /Users/zoe/Developer/babel/node_modules/babel-core/lib/config/loading/files/configuration.js:62:17
    at Array.reduce (native)
    at findConfigs (/Users/zoe/Developer/babel/node_modules/babel-core/lib/config/loading/files/configuration.js:56:76)
    at ConfigChainBuilder.findConfigs (/Users/zoe/Developer/babel/node_modules/babel-core/lib/config/build-config-chain.js:136:28)
    at buildConfigChain (/Users/zoe/Developer/babel/node_modules/babel-core/lib/config/build-config-chain.js:40:15)
    at OptionManager.init (/Users/zoe/Developer/babel/node_modules/babel-core/lib/config/option-manager.js:114:54)
    at manageOptions (/Users/zoe/Developer/babel/node_modules/babel-core/lib/config/option-manager.js:59:30)
    at loadConfig (/Users/zoe/Developer/babel/node_modules/babel-core/lib/config/index.js:20:38)
    at Object.transform (/Users/zoe/Developer/babel/node_modules/babel-core/lib/transformation/pipeline.js:48:37)
    at DestroyableTransform._transform (/Users/zoe/Developer/babel/node_modules/gulp-babel/index.js:36:22)
[12:29:39] Finished 'build' after 768 ms
[12:29:39] Starting 'build-babel-standalone'...
[12:29:39] 'build-babel-standalone' errored after 558 ms
[12:29:39] TypeError: require(...).default is not a function
    at webpackBuild (/Users/zoe/Developer/babel/packages/babel-standalone/src/gulpTasks.js:27:60)
    at Gulp.gulp.task.cb (/Users/zoe/Developer/babel/packages/babel-standalone/src/gulpTasks.js:108:9)
    at module.exports (/Users/zoe/Developer/babel/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/zoe/Developer/babel/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/zoe/Developer/babel/node_modules/orchestrator/index.js:214:10)
    at /Users/zoe/Developer/babel/node_modules/orchestrator/index.js:279:18
    at finish (/Users/zoe/Developer/babel/node_modules/orchestrator/lib/runTask.js:21:8)
    at /Users/zoe/Developer/babel/node_modules/orchestrator/lib/runTask.js:52:4
    at f (/Users/zoe/Developer/babel/node_modules/orchestrator/node_modules/once/once.js:17:25)
    at DestroyableTransform.onend (/Users/zoe/Developer/babel/node_modules/orchestrator/node_modules/end-of-stream/index.js:31:18)
make[1]: *** [build] Error 1
make: *** [bootstrap] Error 2
```
[Dependency error](https://github.com/babel/babel/files/1239971/DependencyError.txt)
[Full `make bootstrap` log here](https://github.com/babel/babel/files/1239957/errorLog.txt)

**Comment by hzoo** [comment]
@pudility where does it say to use npm 3? Oh, make sure you are on the 7.0 branch (that's the default that we are using on github) and we use yarn atm instead of npm (`make boostrap` runs the install). You don't have to run make clean-all it's the first command in `make bootstrap`

**Comment by pudility** [comment]
@hzoo Thanks for the comment, I have cloned and am working in the 7.0 branch, but I currently have 6.26.0 installed. Also, I only ran `make boostrap` (sorry if that was unclear). It says to [use npm 3 under developing here.](https://github.com/babel/babel/blob/master/CONTRIBUTING.md#developing)

**Comment by hzoo** [comment]
What do you mean by 6.26.0 installed though? If you are on the 7.0 branch then the instructions should be different/updated. Either way on 7.0 make bootstrap runs yarn https://github.com/babel/babel/blob/7.0/CONTRIBUTING.md#developing

**Comment by pudility** [comment]
I ran `$ npm install --global babel-cli` to install babel `6.26.0`, but I ran `$ git clone https://github.com/babel/babel`to clone the 7.0 branch. Should I be doing something differently, should I try to install `babel-cli` at a higher version? Thanks for the help!

**Comment by hzoo** [comment]
Ok I'm confused 😄 . Are you trying to develop for the babel codebase or do you have an issue with using Babel? You don't need to install anything globally to develop with babel?

**Comment by pudility** [comment]
Ok thank you so much! But this still does not solve the error I am getting: `TypeError: require(...).default is not a function`

**Comment by pudility** [comment]
Basically, forget `$ npm install --global babel-cli`. I cloned babel, and ran `make boostrap` then I got a bunch of [dependency errors](https://github.com/babel/babel/files/1239971/DependencyError.txt). After I solved those (which I am not sure I did correctly) I got the above error. Thanks again for all the help.

**Comment by hzoo** [comment]
What version of yarn are you using? `yarn --version` check that it's >= 0.28.1

**Comment by pudility** [comment]
ahhh, and there in lies the problem! I am using `0.24.5`. Thank you for the help, Is this something that should/could be added to docs?

**Comment by hzoo** [comment]
It's in the docs at https://github.com/babel/babel/blob/7.0/CONTRIBUTING.md#developing which I thought you were looking at (and I thought the yarn version would error since it's specified in package.json).

if it works great

**Comment by pudility** [comment]
that odd... It does not say it here https://github.com/babel/babel/blob/master/CONTRIBUTING.md#developing

**Comment by hzoo** [comment]
Yeah I was saying how 7.0/master is different (we haven't been developing on that for a long time). But I see how it's confusing and we'll be moving 7.0 to master later so this shouldn't be an issue in the future.

**Comment by pudility** [comment]
Ok great! thanks again for the help.
