### ISSUE TITLE
@babel/core v7.5.5 throw TypeError: helpers(...).ensure is not a function

### ISSUE THREAD

**Issue by JennerChen** [babel/babel#10266]
## Bug Report

**Current Behavior**
After I upgrade @babel/core to v7.5.5, circleci build throw error `TypeError: helpers(...).ensure is not a function`

This error only happen in circleci environment. No error in windows or Mac

**Environment**
- Babel version(s): [v7.5.5]
- Node/npm version: [e.g. Node 10/npm 5]
- OS: [linux]
- How you are using Babel: [`loader`]

**Possible Solution**
The error happen in below line in v7.5.5
https://github.com/babel/babel/blob/fced5cea430cc00e916876b663a8d2a84a5dad1f/packages/babel-core/src/transformation/file/file.js#L207

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/5472912/61847532-9908b180-aedd-11e9-8c96-3a242c363300.png)
[@babel/core v7.5.5 build log](https://circleci.com/gh/freshesx/mogul/607)
[@babel/core v7.5.4 build log](https://circleci.com/gh/freshesx/mogul/603)

**Comment by nicolo-ribaudo** [comment]
Can you share your lockfile?
Ensuring that `@babel/helpers` is v7.5.5 should fix this problem, until we fix it on our side.

**Comment by JennerChen** [comment]
https://github.com/freshesx/mogul/blob/master/yarn.lock @nicolo-ribaudo

**Comment by JLHwung** [comment]
I looks like we come across circular dependencies: `require("@babel/helpers")` returns an unfinished copy.

I notice that `@babel/traverse` is not hoisted to the root dependencies. What it means is that there will be two copies of `@babel/traverse` running. It is not a good news. I would suggest use [yarn-deduplicate] to make dependency graph flat.

[yarn-deduplicate]: https://github.com/atlassian/yarn-deduplicate

**Comment by JennerChen** [comment]
@JLHwung , thank you, yarn-deduplicate fix the problem.

**Comment by Mindaugas-Jacionis** [comment]
I had the same issue in monorepo. The resolution, as simple stupid it might sound, was to `rm -rf node_modules` in all `packages` of monorepo and then run `yarn`/`npm i` at root dir. 

So I assume I had duplicate packages as I was running installs in each package/sub-repo of monorepo.

**Comment by sibelius** [comment]
this is still happening for us on 7.5.5

**Comment by zheeeng** [comment]
Still has this issue

**Comment by hnrchrdl** [comment]
Removing all node_modules and running a fresh install resolved the issue for me.

**Comment by nicolo-ribaudo** [comment]
@sibelius Could you check in your lockfile if every `@babel/helpers` version is >= 7.5.5?

**Comment by sibelius** [comment]
we removed node_modules and webpack build cache, and it is solved

tks

**Comment by bmish** [comment]
I had this same issue and ended up using a yarn resolution in package.json to fix it (a less invasive change than running `yarn-deduplicate`):

```
"resolutions": {
  "@babel/helpers": "^7.6.0"
}
```
