### ISSUE TITLE
Critical dependency: the request of a dependency is an expression after upgrade 7.8 to 7.9

### ISSUE THREAD

**Issue by mrbinr** [babel/babel#11607]
## Project

It about a ReactJS project built with create-react-app

## Bug Report

**Current behavior**
I have a ReactJS code in which there is this part of code which works perfectly 
```
  const render = React.lazy(() => import(`../${type}/render${type}`));
```

**After upgrading babel**

babel/core@7.8.7 to 7.9.0
@babel/plugin-transform-runtime@7.8.3 to 7.9.0
@babel/preset-env@7.8.7 to 7.9.0

i have this error in log compilation : 
```
Critical dependency: the request of a dependency is an expression
```

and then in browser
```
Error: Cannot find module '../my-module'
```

There is something strange, if I replace
```
  const render = React.lazy(() => import(`../${type}/render${type}`));
```
with 
```
  const render = React.lazy(() => Sytem.import(`../${type}/render${type}`));
```
it works again ... 

## Environment
NodeJS 13.14.0

thanks for your help
Best Regards
Pascall

**Comment by nicolo-ribaudo** [comment]
What is your config?

**Comment by mrbinr** [comment]
hi,

I was creating a repo with a newest create-react-app project to explain each step of the problem, but with this newest project there is no problem .. :(
So it seems to be the upgrade of babel from version 7.8.* to 7.9.* which has not been done corretly or may be all packages are not updated ?
Something really strange ...

if someone has a idea about upgrading properly babel in a project ...

nodeJS              13.14.0
npx                 6.14.4
create-react-app    3.3.0

here is the code that works https://github.com/mrbinr/react-dynamic-import-component

**Comment by nicolo-ribaudo** [comment]
Did you eject CRA in the broken project, or is it with the default config?

**Comment by mrbinr** [comment]
no, i did not ejact CRA , it's default configuration

**Comment by JLHwung** [comment]
This issue is related to https://github.com/airbnb/babel-plugin-dynamic-import-node/issues/88. However I can not reproduce this issue in a fresh created CRA apps.

You can try to pin `babel-plugin-dynamic-import-node` to version 2.3.0, but IMO it should not be enabled at all given default react app build configs.

Can you offer a reproduction repo?

**Comment by svewag** [comment]
I also had this issue in my vue project (not vue-cli, not nuxt) when running webpack for client and server build.

* "@babel/core": "7.10.5"
* "@babel/preset-env": "7.10.4"
* "@babel/plugin-transform-runtime": "7.10.5"
* "@babel/plugin-syntax-dynamic-import": "7.8.3"
* "babel-plugin-dynamic-import-node": "2.3.3"

```js
// babel.config.js
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        modules: false,
        debug: false,
        useBuiltIns: false,
        targets: {
          browsers: ['> 1%', 'last 2 versions', 'not ie < 11'],
        },
      },
    ],
  ],
  plugins: [
    [
      '@babel/plugin-transform-runtime',
      {
        helpers: false,
        regenerator: true,
        // new
        useESModules: true,
      },
    ],
    '@babel/plugin-transform-modules-commonjs',
    '@babel/plugin-proposal-class-properties',
    '@babel/plugin-proposal-function-sent',
    '@babel/plugin-proposal-numeric-separator',
    '@babel/plugin-proposal-throw-expressions',
    '@babel/plugin-proposal-optional-chaining',
  ],
  env: {
    server: {
      plugins: ['babel-plugin-dynamic-import-node'],
    },
    client: {
      plugins: ['@babel/plugin-syntax-dynamic-import'],
    },
  },
  comments: true,
}
```

After downgrading babel-plugin-dynamic-import-node to 2.3.0 errors were gone.

**Comment by nicolo-ribaudo** [comment]
You don't need to downgrade: you can completely disable it when you are using webpack.

**Comment by imagoiq** [comment]
I have the same issue on a project using vue-cli. Several part are using

**Comment by nicolo-ribaudo** [comment]
@imagoiq The proper solution is to avoid using a package meant to be used _when targeting Node.js_ if you are targeting webpack. I suggest opening an issue in the `vue-cli` repository.

**Comment by nicolo-ribaudo** [comment]
Closing since this problem was caused by using a plugin when bundling, while that plugin explicitly doesn't support bundling but should only be used when targeting Node.js.
