### ISSUE TITLE
Cannot find module '@babel/runtime-corejs2/core-js/reflect/construct'

### ISSUE THREAD

**Issue by maggiew61** [babel/babel#12988]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

After upgrading from babel 6 to 7, Error occurred in PR deploy phrase. It was working normally in local build.  
This is what I see on pm2 log on K8s
```
Cannot find module '@babel/runtime-corejs2/core-js/reflect/construct'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
at Module.Hook._require.Module.require (/home/y/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
at require (internal/modules/cjs/helpers.js:25:18)
at Object.<anonymous> (/home/y/share/node/manhattan_app/transpile/lib/errorHelper.js:3:26)
at Module._compile (internal/modules/cjs/loader.js:778:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
at Function.Module._load (internal/modules/cjs/loader.js:585:3)
at Module.require (internal/modules/cjs/loader.js:692:17)
```

This is the excerpt from package.json
```
 "devDependencies": {
    "@babel/cli": "^7.0.0",
    "@babel/core": "^7.0.0",
    "@babel/node": "^7.0.0",
    "@babel/plugin-proposal-class-properties": "^7.0.0",
    "@babel/plugin-proposal-decorators": "^7.0.0",
    "@babel/plugin-proposal-do-expressions": "^7.0.0",
    "@babel/plugin-proposal-export-default-from": "^7.0.0",
    "@babel/plugin-proposal-export-namespace-from": "^7.0.0",
    "@babel/plugin-proposal-function-bind": "^7.0.0",
    "@babel/plugin-proposal-function-sent": "^7.0.0",
    "@babel/plugin-proposal-json-strings": "^7.0.0",
    "@babel/plugin-proposal-logical-assignment-operators": "^7.0.0",
    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.0.0",
    "@babel/plugin-proposal-numeric-separator": "^7.0.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0",
    "@babel/plugin-proposal-optional-chaining": "^7.0.0",
    "@babel/plugin-proposal-pipeline-operator": "^7.0.0",
    "@babel/plugin-proposal-throw-expressions": "^7.0.0",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@babel/plugin-syntax-import-meta": "^7.0.0",
    "@babel/plugin-transform-computed-properties": "^7.0.0",
    "@babel/plugin-transform-modules-commonjs": "^7.13.8",
    "@babel/plugin-transform-react-constant-elements": "^7.0.0",
    "@babel/plugin-transform-react-inline-elements": "^7.0.0",
    "@babel/plugin-transform-runtime": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "@babel/preset-react": "^7.0.0",
    "@babel/register": "^7.0.0",
    "@babel/runtime-corejs2": "7.12.5",
    "autoprefixer": "^8.6.5",
    "babel-eslint": "^10.0.2",
    "babel-jest": "^24.8.0",
    "babel-loader": "^8.0.0",
    "babel-plugin-css-modules-transform": "^1.6.2",
    "babel-plugin-import": "^1.12.2",
    "babel-plugin-lodash": "^3.3.4",
    "babel-plugin-rewire-exports": "^0.5.0",
    "clean-css-cli": "^4.1.6",
    "component_ec_nodejs_test_util": "^1.0.6",
    "css-loader": "^3.6.0",
    "deep-freeze": "0.0.1",
    "ectest-accounts": "^0.1.1656",
    "enzyme": "^3.8.0",
    "enzyme-adapter-react-16": "^1.7.1",
    "eslint": "^6.1.0",
    "eslint-config-prettier": "^6.7.0",
    "eslint-plugin-codeceptjs": "^1.0.0",
    "eslint-plugin-json": "^1.4.0",
    "eslint-plugin-prettier": "^3.1.0",
    "eslint-plugin-react": "^7.14.3",
    "eslint-plugin-react-hooks": "^1.6.1",
    "file-loader": "^6.0.0",
    "jest": "^26.6.3",
    "jest-junit": "^3.0.0",
    "mini-css-extract-plugin": "^0.10.0",
    "nodemon": "1.17.3",
    "postcss": "^7.0.32",
    "postcss-easy-import": "^3.0.0",
    "postcss-functions": "^2.1.1",
    "postcss-import": "^10.0.0",
    "postcss-loader": "^2.0.6",
    "postcss-scss": "^1.0.2",
    "postcss-simple-vars": "^4.0.0",
    "pre-commit": "^1.2.2",
    "precss": "^2.0.0",
    "prettier": "^1.19.1",
    "react-test-renderer": "^16.6.3",
    "redux-mock-store": "^1.5.3",
    "request-promise": "^4.2.2",
    "requestretry": "^3.1.0",
    "rimraf": "2.4.3",
    "saucelabs": "^1.5.0",
    "sd-s3-assets-deploy": "^0.4.1",
    "style-loader": "^1.2.1",
    "url-loader": "^0.6.2",
    "wait-for-expect": "^1.1.1",
    "wait-on": "^2.0.2",
    "wdio-screenshot": "^0.6.0",
    "webdriverio": "^4.13.1",
    "webpack": "^4.27.0",
    "webpack-bundle-analyzer": "^3.0.3",
    "webpack-cli": "^3.1.2",
    "webpack-dev-middleware": "^3.4.0",
    "webpack-hot-middleware": "^2.24.3",
    "webpack-manifest-plugin": "^2.0.4"
  },
```

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babelrc_webpack_dev.json`
```
{
  "presets": [
    "@babel/preset-react",
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": "current",
          "browsers": ["ie >= 11"]
        }
      }
    ]
  ],
  "plugins": [
    [
      "@babel/plugin-transform-runtime",
      {
        "corejs": 2,
        "regenerator": true
      }
    ],
    "@babel/plugin-transform-computed-properties",
    "@babel/plugin-proposal-object-rest-spread",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-transform-react-inline-elements",
    "@babel/plugin-transform-react-constant-elements",
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-syntax-import-meta",
    "@babel/plugin-proposal-json-strings",
    [
      "@babel/plugin-proposal-decorators",
      {
        "legacy": true
      }
    ],
    "@babel/plugin-proposal-function-sent",
    "@babel/plugin-proposal-export-namespace-from",
    "@babel/plugin-proposal-numeric-separator",
    "@babel/plugin-proposal-throw-expressions",
    "@babel/plugin-proposal-export-default-from",
    "@babel/plugin-proposal-logical-assignment-operators",
    "@babel/plugin-proposal-optional-chaining",
    [
      "@babel/plugin-proposal-pipeline-operator",
      {
        "proposal": "minimal"
      }
    ],
    "@babel/plugin-proposal-nullish-coalescing-operator",
    "@babel/plugin-proposal-do-expressions",
    "@babel/plugin-proposal-function-bind",
    "lodash"
  ],
  "sourceType": "unambiguous"
}
```

and the above is required and used in 
- Filename: `webpack.config.dev.js`
```
const devBabelLoaderOptions = require('../babel/babelrc_webpack_dev.json')
export default {
  .... 
  },
  plugins: [
 ....
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        include: [path.join(__dirname, '..', 'src')],
        use: [
          {
            loader: 'babel-loader',
            options: {
              ...devBabelLoaderOptions,
              babelrc: false,
              cacheDirectory: true
            }
          }
        ]
      },
```

Filename: `babelrc_webpack_prod.json`
```
{
  "presets": [
    "@babel/preset-react",
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": "current",
          "browsers": ["ie >= 11"]
        },
        "include": ["@babel/plugin-transform-shorthand-properties"]
      }
    ]
  ],
  "plugins": [
    [
      "@babel/plugin-transform-runtime",
      {
        "corejs": 2,
        "regenerator": true
      }
    ],
    "@babel/plugin-transform-modules-commonjs",
    "@babel/plugin-transform-computed-properties",
    "@babel/plugin-proposal-object-rest-spread",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-transform-react-inline-elements",
    "@babel/plugin-transform-react-constant-elements",
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-syntax-import-meta",
    "@babel/plugin-proposal-json-strings",
    [
      "@babel/plugin-proposal-decorators",
      {
        "legacy": true
      }
    ],
    "@babel/plugin-proposal-function-sent",
    "@babel/plugin-proposal-export-namespace-from",
    "@babel/plugin-proposal-numeric-separator",
    "@babel/plugin-proposal-throw-expressions",
    "@babel/plugin-proposal-export-default-from",
    "@babel/plugin-proposal-logical-assignment-operators",
    "@babel/plugin-proposal-optional-chaining",
    [
      "@babel/plugin-proposal-pipeline-operator",
      {
        "proposal": "minimal"
      }
    ],
    "@babel/plugin-proposal-nullish-coalescing-operator",
    "@babel/plugin-proposal-do-expressions",
    "@babel/plugin-proposal-function-bind",
    "lodash",
    [
      "import",
      {
        "libraryName": "antd",
        "libraryDirectory": "es",
        "style": false
      },
      "ant"
    ]
  ]
}
```
and the above is required and used in 
- Filename: `webpack.config.prod.js`
```
const prodBabelLoaderOptions = require('../babel/babelrc_webpack_prod.json')

export default {
  ...
  plugins: 
...
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        include: [path.join(__dirname, '..', 'src')],
        use: [
          {
            loader: 'babel-loader',
            options: {
              ...prodBabelLoaderOptions,
              babelrc: false
            }
          }
        ]
      },
```

- Filename: `.babelrc`

```
{
    "presets": [
      "@babel/preset-react",
      [
        "@babel/preset-env",
        {
          "targets": {
            "node": "current",
            "browsers": [
              "ie >= 11"
            ]
          }
        }
      ]
    ],
    "plugins": [
      [
        "css-modules-transform",
        {
          "generateScopedName": "[local]__[hash:base64:5]",
          "extensions": [
            ".css"
          ],
          "processorOpts": "./babel/processor.options.js"
        }
      ],
      [
        "@babel/plugin-transform-runtime",
        {
          "corejs": 2,
          "regenerator": true
        }
      ],
      "@babel/plugin-transform-computed-properties",
      "@babel/plugin-proposal-object-rest-spread",
      "@babel/plugin-proposal-class-properties",
      "@babel/plugin-transform-react-inline-elements",
      "@babel/plugin-transform-react-constant-elements",
      "lodash",
      "@babel/plugin-syntax-dynamic-import",
      "@babel/plugin-syntax-import-meta",
      "@babel/plugin-proposal-json-strings",
      [
        "@babel/plugin-proposal-decorators",
        {
          "legacy": true
        }
      ],
      "@babel/plugin-proposal-function-sent",
      "@babel/plugin-proposal-export-namespace-from",
      "@babel/plugin-proposal-numeric-separator",
      "@babel/plugin-proposal-throw-expressions",
      "@babel/plugin-proposal-export-default-from",
      "@babel/plugin-proposal-logical-assignment-operators",
      "@babel/plugin-proposal-optional-chaining",
      [
        "@babel/plugin-proposal-pipeline-operator",
        {
          "proposal": "minimal"
        }
      ],
      "@babel/plugin-proposal-nullish-coalescing-operator",
      "@babel/plugin-proposal-do-expressions",
      "@babel/plugin-proposal-function-bind"
    ],
    "sourceType": "unambiguous"
  }  
```

**Environment**

- Babel version(s): [v7]
- Node/npm version: [e.g. Node 10.21.0/npm 6.14.4]
- OS: [macOS 10.15.7]
- Monorepo: [no]
- How you are using Babel: [webpack]

**I've been banging my head for days to try to fix this. Please suggest how to fix this problem. Thank you.**

**Comment by nicolo-ribaudo** [comment]
Doesn't this file exist? :thinking: 
https://unpkg.com/browse/@babel/runtime-corejs2@7.12.5/core-js/reflect/construct.js

**Comment by maggiew61** [comment]
> Doesn't this file exist on your file system? 🤔
> https://unpkg.com/browse/@babel/runtime-corejs2@7.12.5/core-js/reflect/construct.js

In the text above, it is requiring `core-js/library/fn/reflect/construct`
But I just realized that I don't have that under my node_module. This is what I have under 
`my_project/node_modules/core-js` There is no `library`. Could that be the issue🤔 
<img width="244" alt="Screen Shot 2021-03-10 at 3 29 50 AM" src="https://user-images.githubusercontent.com/25575482/110526554-e6886f80-8150-11eb-8f01-4a70f9858f68.png">

**Comment by maggiew61** [comment]
solved. 
`@babel/runtime-corejs2` should be under `dependency` not `devDependency` in package.json as per [Babel guide](https://babeljs.io/docs/en/babel-runtime-corejs2#usage). During the production build, `@babel/runtime-corejs2` was not built inside the node_modules and thus produced the error.
