### PR TITLE
Catch error when fs does not exist

### LINKED ISSUE #4778: x.default.existsSync is not a function
Trying to compile code with Babel 6.18.0 results in a TypeError: x.default.existsSync is not a function
This can be reproduced on http://babeljs.io/repl/.
It was probably caused by https://github.com/babel/babel/pull/4731

### PR DESCRIPTION
**Pull request by danez**
| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          | y?
| Major: Breaking Change?  | n
| Minor: New Feature?      | n
| Deprecations?            | n
| Spec Compliancy?         n| 
| Tests Added/Pass?        | y
| Fixed Tickets            | Fixes #4778, Fixes #4781, Fixes babel/babel-standalone#64
| License                  | MIT
| Doc PR                   | 
| Dependency Changes       | 

This just changes the error message from
```
_fs2.default.existsSync is not a function
```

to 

```
You are using babel in an environment that does not include filesystem access. Ensure to disable .babelrc lookup by setting `babelrc: false` in your config.
```

### CODE REVIEW

File: packages/babel-core/src/transformation/file/options/build-config-chain.js [hunk 1]
```diff
@@ -13,12 +13,21 @@ const PACKAGE_FILENAME = "package.json";
...
-  } else {
-    return cached;
+  if (existsCache[filename] == null) {
+    try {
+      existsCache[filename] = fs.existsSync(filename);
+    } catch (e) {
+      if (typeof fs.existsSync !== "function") {
+        throw new Error(
+          "You are using babel in an environment that does not include filesystem access. " +
+          "Ensure to disable .babelrc lookup by setting `babelrc: false` in your config."
```
Comment (existentialism) [inline packages/babel-core/src/transformation/file/options/build-config-chain.js]: Maybe:

> You can disable .babelrc lookup by setting

**Comment by hzoo** [comment]
Great suggestion 👍

File: packages/babel-core/src/transformation/file/options/build-config-chain.js (hunk 1 above)
Comment (hzoo) [inline packages/babel-core/src/transformation/file/options/build-config-chain.js]: Do we even need to put this check in the catch? we could just check before the actual call itself or is this better?

Comment (danez) [inline packages/babel-core/src/transformation/file/options/build-config-chain.js]: ok fixed

**Comment by hzoo** [comment]
Do we even need to put this check in the catch? we could just check before the actual call itself or is this better?

File: packages/babel-core/src/transformation/file/options/build-config-chain.js (hunk 1 above)
Comment (danez) [inline packages/babel-core/src/transformation/file/options/build-config-chain.js]: Hmm I thought it might be better to do it in the catch as in 99,9% of the cases the check is useless as babel i usually used in node, but probably deopt of v8 because of try catch hurts more.

**Comment by danez** [comment]
Hmm I thought it might be better to do it in the catch as in 99,9% of the cases the check is useless as babel is usually used in node, but probably deopt of v8 because of try catch hurts more.

So I changed it to do it without try-catch.

**Comment by hzoo** [comment]
yeah try/catch does deopt - I thought extracting to another function would make it not deopt. I like this better though

File: packages/babel-core/src/transformation/file/options/build-config-chain.js [hunk 2]
```diff
@@ -13,12 +13,18 @@ const PACKAGE_FILENAME = "package.json";
 const BABELIGNORE_FILENAME = ".babelignore";
 
 function exists(filename) {
-  const cached = existsCache[filename];
-  if (cached == null) {
-    return existsCache[filename] = fs.existsSync(filename);
-  } else {
-    return cached;
+  if (existsCache[filename] == null) {
+    if (typeof fs.existsSync !== "function") {
```
Comment (hzoo) [inline packages/babel-core/src/transformation/file/options/build-config-chain.js]: We could even make this check outside the function right?

Comment (danez) [inline packages/babel-core/src/transformation/file/options/build-config-chain.js]: Not in the global context, as we don't know if people already have babelrc: false, but we could do it [here](https://github.com/danez/babel/blob/429ca92412dcadd566ef23e63f2e349e67a685de/packages/babel-core/src/transformation/file/options/build-config-chain.js#L36) as earliest point in this file.

Comment (danez) [inline packages/babel-core/src/transformation/file/options/build-config-chain.js]: Though it might be nice to have it near the actual call, so in case this gets ever changed or removed it is obvious that the error also needs to be adjusted.

Comment (danez) [inline packages/babel-core/src/transformation/file/options/build-config-chain.js]: Do you have an idea where it could go?

Comment (hzoo) [inline packages/babel-core/src/transformation/file/options/build-config-chain.js]: Yeah I was thinking more like 

```js
const IsNotNode = typeof fs.existsSync !== "function")

function exists(filename) {
  if (existsCache[filename] == null) {
    if (isNotNode) {}
  }
}
```

**Comment by loganfsmyth** [comment]
Happy to land this, but FYI on my config refactoring branch, which I'm hoping to post in the next few days, I've split this code up using the `browser` package.json field so Webpack/Browserify builds won't even try to load `fs`.

**Comment by danez** [comment]
@loganfsmyth That is even better

**Comment by hzoo** [comment]
so are we closing this?
