### ISSUE TITLE
[Bug]: Async generators with default parameters compile to invalid code

### ISSUE THREAD

**Issue by codebutler** [babel/babel#15145]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```js
export async function * foo (p = 1) {
  yield "hello";
}
for await (const x of foo()) {
  console.log(x);
}
```

### Current and expected behavior

With babel v7.17.12, the above code is compiled to:

```js
async function* foo(p) {
  if (p === void 0) {
    p = 1;
  }

  yield "hello";
}

for await (const x of foo()) {
  console.log(x);
}
```

When run with node, this prints `hello` as expected.

With v7.20.2, the compiled code is:

```js
async function foo(p) {
  if (p === void 0) {
    p = 1;
  }
  return async function* () {
    yield "hello";
  }();
}
for await (const x of foo()) {
  console.log(x);
}
```

This throws an exception:

```
Uncaught TypeError: foo(...) is not a function or its return value is not async iterable
```

### Environment

Turn "Bug Fixes" OFF in REPL to reproduce.

### Possible solution

Possible regression caused by #15081 ?
