### ISSUE TITLE
Error with  babel/register after updating to 6.0.2

### ISSUE THREAD

**Issue by ndaidong** [babel/babel#2660]
Hi eveybody, 

Did anyone get the error as below?

```
$ node server.js 
module.js:339
    throw err;
    ^

Error: Cannot find module 'babel/register'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/var/www/itravel/rest/server.js:5:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
```

It happens after I updated babel to 6.0.2.  I've also tried to do the following things:

- remove entirely "node_modules" and re-install all modules
- install "babel" in global scope
- use "babel/core" instead of "babel"
- use require('babel-core/register') insteaf of require('babel/register');

Nothing works.

Everything is OK if I downgrade back to 5.8.2

How I can work with latest version of babel without this issue? Thanks for any help.

**Comment by thejameskyle** [comment]
Use `babel-core/register` not `babel/register`

**Comment by loganfsmyth** [comment]
> <p align="center">For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.</p>

**Comment by ndaidong** [comment]
@thejameskyle As I've described, require('babel-core/register') also does not work in my case.

```
module.js:339
    throw err;
    ^

Error: Cannot find module 'babel-core/register'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/var/www/itravel/rest/server.js:5:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
```

**Comment by thejameskyle** [comment]
Just tried it out and it works for me, please visit the Slack channel for support.

**Comment by ndaidong** [comment]
It's strange! I've joint channel. Thank you, James.
