### PR TITLE
Make sure to publish all the necessary files

### LINKED ISSUE #12816: @babel/runtime@7.12.17 Cannot find module 'node_modules/@babel/runtime/helpers/interopRequireWildcard.js'
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

Rollup fails when updating from 7.12.16 --> 7.12.17

~I'll try to throw up a repo to reproduce shortly, but wanted to raise this ASAP since a handful of my CI builds fail with this update.~

_EDIT: Reproducible here. See [Instructions](https://github.com/ryanvanoss/babel-issue-12816/blob/main/README.md#instructions)._
- https://github.com/ryanvanoss/babel-issue-12816

**Expected behavior**

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `.babelrc.json`

```js
{
  "plugins": ["@babel/plugin-transform-runtime"],
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": "current"
        }
      }
    ]
  ]
}

```

**Environment**

```
  System:
    OS: macOS 11.2.1
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    npm: 6.14.10 - /usr/local/bin/npm
  npmPackages:
    @babel/core: ^7.12.16 => 7.12.17 
    @babel/plugin-transform-runtime: ^7.12.15 => 7.12.17 
    @babel/preset-env: ^7.12.16 => 7.12.17 
    @babel/runtime: ^7.12.13 => 7.12.17 
    babel-jest: ^26.6.3 => 26.6.3 
    eslint: ^7.20.0 => 7.20.0 
    jest: ^26.6.3 => 26.6.3 
```

**Possible Solution**

**Additional context**

Looks like your CI is failing, so perhaps some more details there: https://github.com/babel/babel/runs/1927910861

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #12816
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

Rather than special-casing `lib` and `LICENSE` files, lets just add everything to the artifact so that we don't accidentally miss files.

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
I'm merging this without reviews because currently every project depending on `@babel/runtime` is broken, I'll release a patch soon.

**Review by JLHwung — COMMENTED** [review]
👍
