### ISSUE TITLE
@babel/runtime@7.12.17 Cannot find module 'node_modules/@babel/runtime/helpers/interopRequireWildcard.js'

### ISSUE THREAD

**Issue by ryanvanoss** [babel/babel#12816]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

Rollup fails when updating from 7.12.16 --> 7.12.17

~I'll try to throw up a repo to reproduce shortly, but wanted to raise this ASAP since a handful of my CI builds fail with this update.~

_EDIT: Reproducible here. See [Instructions](https://github.com/ryanvanoss/babel-issue-12816/blob/main/README.md#instructions)._
- https://github.com/ryanvanoss/babel-issue-12816

**Expected behavior**

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `.babelrc.json`

```js
{
  "plugins": ["@babel/plugin-transform-runtime"],
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": "current"
        }
      }
    ]
  ]
}

```

**Environment**

```
  System:
    OS: macOS 11.2.1
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    npm: 6.14.10 - /usr/local/bin/npm
  npmPackages:
    @babel/core: ^7.12.16 => 7.12.17 
    @babel/plugin-transform-runtime: ^7.12.15 => 7.12.17 
    @babel/preset-env: ^7.12.16 => 7.12.17 
    @babel/runtime: ^7.12.13 => 7.12.17 
    babel-jest: ^26.6.3 => 26.6.3 
    eslint: ^7.20.0 => 7.20.0 
    jest: ^26.6.3 => 26.6.3 
```

**Possible Solution**

**Additional context**

Looks like your CI is failing, so perhaps some more details there: https://github.com/babel/babel/runs/1927910861

**Comment by JCVanDam** [comment]
I have the same error.

**Comment by KATT** [comment]
here's a very unhelpful +1 on having the same error 😅

**Comment by samvv** [comment]
Is there a fix? For some reason I'm getting the same error even when I `rm -r node_modules` and downgrade the `@babel/runtime` dependency.

**Comment by mariuslundgard** [comment]
This fixed it for us (note that there's no `^`):

```
  "devDependencies": {
    "@babel/runtime": "7.12.13",
    ...
  }
```

**Comment by SoloJiang** [comment]
+1

**Comment by samvv** [comment]
Removing the `^` was what I needed, thanks!

**Comment by SoloJiang** [comment]
May be there need rollback？

**Comment by nicolo-ribaudo** [comment]
I'm looking at this

**Comment by ryanvanoss** [comment]
<cite>@nicolo-ribaudo</cite>
> I'm looking at this

Thanks @nicolo-ribaudo. In case you missed this in between edits, here's a simple repo to reproduce:

https://github.com/ryanvanoss/babel-issue-12816

**Comment by Stono** [comment]
`npm install @babel/runtime@7.12.13` resolves this so looks like a regression

**Comment by nicolo-ribaudo** [comment]
I tagged `7.12.13` as `latest` on npm, hopefully it doesn't download 7.12.17. I know what causes the problem, I'll open a PR soon.

**Comment by yoavniran** [comment]
Seeing this now when trying to build a project using Gatsby. The project itself doesnt depend on babel directly...

**Comment by aiji42** [comment]
The same bug appears in projects using react-script.

**Comment by SoloJiang** [comment]
@nicolo-ribaudo good job!

**Comment by nicolo-ribaudo** [comment]
PR: https://github.com/babel/babel/pull/12817

**Comment by nicolo-ribaudo** [comment]
It's being released by https://github.com/babel/babel/actions/runs/578672005.

I'm only 95% sure that it fixes the bug, but for sure it doesn't make it worse :sweat_smile:

**Comment by aiji42** [comment]
Thanks for the quick fix.

**Comment by csvan** [comment]
Not sure if this is covered by the fix, but all our eslint stuff is failing on

```
Cannot find module '/workdir/node_modules/@babel/runtime/helpers/extends.js'
```

**Comment by nicolo-ribaudo** [comment]
Yes it's the same thing.

**Comment by csvan** [comment]
Awesome, thanks for the quick fix @nicolo-ribaudo !

**Comment by nicolo-ribaudo** [comment]
The helpers are back!
https://unpkg.com/browse/@babel/runtime@7.12.18/helpers/
