### ISSUE TITLE
root-mode for babel-node

### ISSUE THREAD

**Issue by zefexdeveloper** [babel/babel#9137]
I'm using Babel 7 and I have a monorepo with lerna and yarn workspaces, I could configure the script like this: `babel src --root-mode upward --out-dir dist --delete-dir-on-start` and it works really nice, however I want to use `nodemon` with `babel-node` but I noticed that I can't specify `--root-mode` for `babel-node`, what can I do to solve that?

`nodemon --legacy-watch --exec babel-node -- src/index`

**Comment by nicolo-ribaudo** [comment]
It should work in @babel/node 7.2.0 (https://github.com/babel/babel/pull/9078)

**Comment by zefexdeveloper** [comment]
I'm using 7.2.0 but still not working.
`babel-node --root-mode upward src/index.js`

> internal/modules/cjs/loader.js:605
>    throw err;
>    ^
>
> Error: Cannot find module 'C:\Users\ZD\Desktop\acme\packages\server\upward'

**Comment by nicolo-ribaudo** [comment]
What does `npx nls why @babel/cli` say? Maybe for some reason it is loading an older version.

**Comment by zefexdeveloper** [comment]
>   Who required @babel/cli:
> acme > @babel/cli@^7.2.0

When I run `babel-node -- src/index.js --root-mode upward` making `--root-mode` the last param it runs the command but it doesn't seem to load the config, it throws me an error:

> (function (exports, require, module, __filename, __dirname) { import express from 'express'
> SyntaxError: Unexpected identifier

It's only working for `build` using `babel src --root-mode upward --out-dir dist`

**Comment by loganfsmyth** [comment]
Can you try
```
babel-node --root-mode upward src/index.js 
```

**Comment by zefexdeveloper** [comment]
@loganfsmyth 

> yarn babel-node --root-mode upward src/index.js

> internal/modules/cjs/loader.js:605
> throw err;
> Error: Cannot find module 'C:\Users\ZD\Desktop\acme\packages\server\upward'

It's trying to load `upward` as a module

**Comment by nicolo-ribaudo** [comment]
It is
```
babel-node --root-mode=upward src/index.js 
```

For some reason we expect options in the `--name=value` format in `@babel/node`:
https://github.com/babel/babel/blob/4fdb71151f30067845ce36eb9a9ec14207606fe6/packages/babel-node/src/babel-node.js#L38
