### ISSUE TITLE
Inconsistent failure "cannot find module" after upgrading to babel 7.4

### ISSUE THREAD

**Issue by shaunluttin** [babel/babel#9932]
## Bug Report

**Current Behavior**

This bug surfaced after upgrade to babel 7.4 from 7.1. If we run jest about ten times, the tests will sometimes fail. I appreciate that this bug report might be more appropriate for the `jest` GitHub organization and I also posted it there https://github.com/facebook/jest/issues/8404.

Example Failure 1
```
 FAIL  src/__tests__/one.unit.test.4.js                              
  ? Test suite failed to run                                         
                                                                     
    Cannot find module 'split-string'                                
                                                                     
      at Object.<anonymous> (node_modules/braces/lib/utils.js:3:19)  
```

Example Failure 2
```
 FAIL  src/one.unit.test.1.js
   ? Test suite failed to run

       Cannot find module './lib/compilers'

             at Object.<anonymous> (node_modules/braces/index.js:15:17)
```
                                                                     
**Input Code**

```bash
git clone git@github.com:RubikonBlockchain/babel-bug-reproduction.git
cd babel-bug-reproduction
npm install
for run in {1..10}; do npm run test; done;
```

https://github.com/RubikonBlockchain/babel-bug-reproduction

**Expected behavior/code**

The tests run without failure and can find files that exist.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
module.exports = function (api) {
  api.env();
  const presets = [
    [
      "@babel/preset-env",
      {
        targets: {
          node: "8.16.0"
        },
        useBuiltIns: "usage",
        corejs: 3,
      }
    ]
  ];

  return { presets };
}
```

**Environment**
- Babel version(s): 7.4.4
- Node/npm version: Node 8.16.0/npm 6.4.1
- OS: Windows Subsystem for Linux (Ubuntu) and also on Windows 10
- Monorepo: no
- How you are using Babel: `cli` `babel-jest`

**Comment by shaunluttin** [comment]
I was able to reproduce the issue without babel using only jest.
