### PR TITLE
Fix helper-builder-react-jsx compat with Babel 7.9

### LINKED ISSUE #14884: [Bug]: compile crash (regression?) TypeError: pass.get(...) is not a function; plugin-transform-react-jsx 7.9, helper-builder-react-jsx 7.18
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```
# using latest published nwb v0.25.2
$ npx nwb new react-component my-component
$ cd my-component
$ npm install
$ npm start

Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: /tmp/gg/my-component/src/index.js: pass.get(...) is not a function
    at Object.post (/tmp/gg/my-component/node_modules/@babel/plugin-transform-react-jsx/lib/transform-classic.js:48:47)
    at buildElementCall (/tmp/gg/my-component/node_modules/@babel/helper-builder-react-jsx/lib/index.js:167:12)
    at PluginPass.exit (/tmp/gg/my-component/node_modules/@babel/helper-builder-react-jsx/lib/index.js:53:24)
    at newFn (/tmp/gg/my-component/node_modules/@babel/traverse/lib/visitors.js:181:21)
    at NodePath._call (/tmp/gg/my-component/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/tmp/gg/my-component/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/tmp/gg/my-component/node_modules/@babel/traverse/lib/path/context.js:109:8)
    at TraversalContext.visitQueue (/tmp/gg/my-component/node_modules/@babel/traverse/lib/context.js:105:16)
    at TraversalContext.visitMultiple (/tmp/gg/my-component/node_modules/@babel/traverse/lib/context.js:74:17)
    at TraversalContext.visit (/tmp/gg/my-component/node_modules/@babel/traverse/lib/context.js:131:19)
    at traverseNode (/tmp/gg/my-component/node_modules/@babel/traverse/lib/traverse-node.js:24:17)
    at NodePath.visit (/tmp/gg/my-component/node_modules/@babel/traverse/lib/path/context.js:107:52)
    at TraversalContext.visitQueue (/tmp/gg/my-component/node_modules/@babel/traverse/lib/context.js:105:16)
    at TraversalContext.visitSingle (/tmp/gg/my-component/node_modules/@babel/traverse/lib/context.js:79:19)
    at TraversalContext.visit (/tmp/gg/my-component/node_modules/@babel/traverse/lib/context.js:133:19)
    at traverseNode (/tmp/gg/my-component/node_modules/@babel/traverse/lib/traverse-node.js:24:17)

$ npm ls | grep jsx
│ ├─┬ @babel/plugin-transform-react-jsx@7.9.4
│ │ ├─┬ @babel/helper-builder-react-jsx@7.18.6
```

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

works with:
```
    "@babel/helper-builder-react-jsx": "7.16.7"
```

doesn't work with:
```
    "@babel/helper-builder-react-jsx": "7.18.6"
```

### Environment

plugin-transform-react-jsx 7.9
helper-builder-react-jsx 7.18

### Possible solution

edit line 53 of node_modules/@babel/helper-builder-react-jsx/lib/index.js +53 to revert https://github.com/babel/babel/commit/b1e73d6f961065c56427ffa89c130beea8321d3b#diff-3670f8045f2c739225a4da543e477ae1fca436a1ab52d5fdbee5771bf5f51b2cR68
```
-       const callExpr = buildElementCall(path, state.file);
+       const callExpr = buildElementCall(path, file);
```

### Additional context

it seems that the variable that was refactored in b1e73d6f961065c56427ffa89c130beea8321d3b (file -> state.file) in helper-builder-react-jsx/lib/index.js file was just wrongly named, because it is passed to https://github.com/babel/babel/blob/v7.9.0/packages/babel-plugin-transform-react-jsx/src/transform-classic.js#L43 which uses the get() method from state ?

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #14884 
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

Fix a compatibility issue between `helper-builder-react-jsx` 7.18 and `transform-react-jsx` 7.9, introduced in #14601. Added behaviour tests to ensure the options interfaces are correct.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14886"></a>

### CODE REVIEW

File: packages/babel-helper-builder-react-jsx/src/index.ts [hunk 1]
```diff
@@ -79,7 +79,7 @@ You can set \`throwIfNamespace: false\` to bypass this warning.`,
           "Fragment tags are only supported in React 16 and up.",
         );
       }
-      const callExpr = buildFragmentCall(path, state.file);
+      const callExpr = buildFragmentCall(path, state);
```
Comment (JLHwung) [inline packages/babel-helper-builder-react-jsx/src/index.ts:82]: This is the key fix suggested in https://github.com/babel/babel/issues/14884#issue-1351943248, other source changes are refactors so that the variable names are consistent with the typings.

Comment (liuxingbaoyu) [reply packages/babel-helper-builder-react-jsx/src/index.ts:82]: One small question: `state.file.get` also exists, why does it throw `pass.get(...) is not a function`?

**Review by liuxingbaoyu — APPROVED** [review]

**Review by nicolo-ribaudo — APPROVED** [review]
