### PR TITLE
Fix compilation of parameters in async generators

### LINKED ISSUE #15145: [Bug]: Async generators with default parameters compile to invalid code
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```js
export async function * foo (p = 1) {
  yield "hello";
}
for await (const x of foo()) {
  console.log(x);
}
```

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

With babel v7.17.12, the above code is compiled to:

```js
async function* foo(p) {
  if (p === void 0) {
    p = 1;
  }

  yield "hello";
}

for await (const x of foo()) {
  console.log(x);
}
```

When run with node, this prints `hello` as expected.

With v7.20.2, the compiled code is:

```js
async function foo(p) {
  if (p === void 0) {
    p = 1;
  }
  return async function* () {
    yield "hello";
  }();
}
for await (const x of foo()) {
  console.log(x);
}
```

This throws an exception:

```
Uncaught TypeError: foo(...) is not a function or its return value is not async iterable
```

### Environment

Turn "Bug Fixes" OFF in REPL to reproduce.

### Possible solution

Possible regression caused by #15081 ?

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #15145
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

We cannot compile async generators to async functions, because async generators don't return promises.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15146"></a>

### CODE REVIEW

**Review by liuxingbaoyu — APPROVED** [review]

**Review by JLHwung — APPROVED** [review]

**Comment by liuxingbaoyu** [comment]
Hint: CI errors are related.

File: packages/babel-plugin-transform-parameters/test/fixtures/regression/15145/options.json [hunk 1]
```diff
@@ -0,0 +1,6 @@
+{
+  "plugins": ["transform-parameters"],
+  "parserOpts": {
+    "allowReturnOutsideFunction": true
+  }
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-parameters/test/fixtures/regression/15145/options.json:5]:
```suggestion
  },
  "minNodeVersion": "10.0.0"
```
