### ISSUE TITLE
x.default.existsSync is not a function

### ISSUE THREAD

**Issue by jochenberger** [babel/babel#4778]
Trying to compile code with Babel 6.18.0 results in a TypeError: x.default.existsSync is not a function
This can be reproduced on http://babeljs.io/repl/.
It was probably caused by https://github.com/babel/babel/pull/4731

**Comment by hey99xx** [comment]
I'm seeing the same error. babeljs repl website is completely broken at this time.

**Comment by danez** [comment]
This error should not happen when using babel in node. We will look into the issue in the repl.

**Comment by danez** [comment]
I disabled the .babelrc lookup in the repl and it works again.

**Comment by Daniel15** [comment]
Sorry about that! All my unit tests on babel-standalone were passing so I didn't notice that it was broken. Turns out it only broke if you pass a `filename` to `Babel.transform`. I'll add a unit test for that particular scenario.
