### ISSUE TITLE
It's too easy to make the build inconsistent

### ISSUE THREAD

**Issue by monsanto** [babel/babel#1353]
I think it would help getting contributors involved if the build system was friendlier. I was `git bisect`ing earlier and found myself in a state where nothing short of deleting the `lib` folder would make Babel work.

In fact, this is easily reproducible:

```
git checkout v4.7.16
make
git checkout master
make
babel

/home/monsanto/source/babel2/lib/babel/traversal/scope.js:101
    var cached = path.getData("scope");
                      ^
TypeError: undefined is not a function
```

Perhaps `build-core` (the default target) should delete `lib` before running? It doesn't seem to work incrementally so this wouldn't affect speed.

Another option would be to use a build tool like [tup](http://gittup.org/tup/) which will guarantee your build is always consistent. It also does file watching/incremental builds/parallel builds. In my experience the only downside of using tup with Babel is that tup is a traditional process-based build system, and spinning up Babel processes is expensive because of the huge startup time.

**Comment by sebmck** [comment]
> Perhaps `build-core` (the default target) should delete `lib` before running?

Sounds good to me!

> ...spinning up Babel processes is expensive because of the huge startup time.

Yeah, startup time is pretty annoying. Hopefully in the future it can be low enough where it wont be an issue at all.
