### ISSUE TITLE
[Bug]: React native main.jsbundle does not exists on archive

### ISSUE THREAD

**Issue by Bardiamist** [babel/babel#16100]
### How are you using Babel?

React native

### Configuration file name

babel.config.js

### Configuration

```js
module.exports = (api) => {
  const plugins = [
    [
      'module-resolver',
      {
        root: ['./'],
        alias: {
          '~': './src',
        },
      },
    ],
    'babel-plugin-macros',
  ];

  if (api.env() !== 'development') {
    plugins.push('transform-remove-console');
  }

  plugins.push('react-native-reanimated/plugin');

  return {
    presets: ['module:metro-react-native-babel-preset'],
    plugins,
  };
};

```

### Current and expected behavior

main.jsbundle should be bundled

### Environment

- "react-native": "0.72.6"
- "react-native-reanimated": "3.5.4"
-  "@babel/core": "7.23.3"
- "@babel/preset-env": "7.23.3"

### Possible solution

Revert `@babel/core` and `@babel/preset-env` to 7.23.2

### Additional context

main.jsbundle does not exists when archive iOS release app after update `@babel/core` and `@babel/preset-env` from 7.23.2 to 7.23.3

Error:
```
command failed with exit status 65 (set -o pipefail && xcodebuild "archive" "-workspace" "/Users/[REDACTED]/git/ios/myproj.xcworkspace" "-scheme" "myproj" "-configuration" "Release" "-xcconfig" "/var/folders/47/vv4z818x0k14x2f1nlpd8ktc0000gn/T/2691548353/temp.xcconfig" "-archivePath" "/var/folders/47/vv4z818x0k14x2f1nlpd8ktc0000gn/T/xcodeArchive984168353/myproj.xcarchive" "-destination" "generic/platform=iOS" | xcpretty):
error: File /Users/[REDACTED]/Library/Developer/Xcode/DerivedData/myproj-anwnflguitnmtpdzvggmsmvhofsr/Build/Intermediates.noindex/ArchiveIntermediates/myproj/BuildProductsPath/Release-iphoneos/myproj.app/main.jsbundle does not exist
```

Everything works during development.

Maybe related, today when tried to find this problem I got once:
```
error: node_modules/react-native-gesture-handler/src/handlers/gestures/hoverGesture.ts: /Users/bardiamist/Documents/myproj/myproj-mobile/node_modules/react-native-gesture-handler/src/handlers/gestures/hoverGesture.ts: [Reanimated] Babel plugin exception: Error: Cannot find module '@babel/plugin-proposal-optional-chaining'
```

**Comment by liuxingbaoyu** [comment]
Can you provide a repository to reproduce?

**Comment by Bardiamist** [comment]
>Can you provide a repository to reproduce?

Unfortunatelly no. Project is big. I even don't build it on my machine. We use Bitrise. Was difficult to localize this problem. Hope you will find possible problem. It's ok for me to rerert for now. If you need I can try to run/test fixes.

Also will be helpful to find whick command now bundle main.jsbundle for release in React native.

**Comment by liuxingbaoyu** [comment]
To be honest, it looks like there are currently no babel related failures, there don't seem to be output file related changes in `v7.23.3`, and if it is indeed a regression of babel, I suspect it is being glossed over. (In any case, babel will not directly cause the file to not exist)
It would be great if you could find out how babel affects the build!

**Comment by Bardiamist** [comment]
Yesteray react-native 0.72.7 is out. I updated it and it works with babel 7.23.3. Maybe they handled somehing in cli.
