### ISSUE TITLE
babel-node -r no longer supports implied ./ in paths since 7.7.7 (probably OK but undocumented)

### ISSUE THREAD

**Issue by serhalp** [babel/babel#12513]
## Bug Report

- [x] I would like to work on a fix!

**Current behavior**

See this branch demonstrating the regression: https://github.com/serhalp/babel-bug-introduced-by-10871/commit/1d7fe1019d0f991c324b77b57f37a808209c6671.

Basically, since https://github.com/babel/babel/pull/10871 introduced an "internal" change to how `babel-node` resolves arguments to `-r`/`--require`, paths without a leading `./` or `../` can no longer be found in the current working directory / babel root.

**Input Code**

Given `foo.js` in the current working directory,
```sh
babel-node --require foo.js bar.js
```
fails with an error like:
```
./babel-bug-introduced-by-10871/node_modules/resolve/lib/sync.js:92
    throw err;
    ^

Error: Cannot find module 'foo.js' from './babel-bug-introduced-by-10871'
    at Function.resolveSync [as sync] (./babel-bug-introduced-by-10871/node_modules/resolve/lib/sync.js:90:15)
    at Object.<anonymous> (./babel-bug-introduced-by-10871/node_modules/@babel/node/lib/_babel-node.js:158:32)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND'
```

while
```sh
babel-node --require ./foo.js bar.js
```

works just fine.

This started failing in @babel/node@7.7.7 and still fails on the latest version (7.12.10). It worked just fine up until and including 7.7.4.

**Expected behavior**

I would expect both examples above to behave identically, as they did in versions up to 7.7.4, at least _given the release notes for this version_.

You can see a repro repo showing it working in 7.7.4 here: https://github.com/serhalp/babel-bug-introduced-by-10871.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

(irrelevant, can repro out of the box with no config)

**Environment**

- Babel version(s): 7.7.7 up to current (7.12.10)
- Node/npm version: node 12.18.3, yarn 1.9.4
- OS: macOS 10.15.7 / Ubuntu 16.04.6
- Monorepo: no
- How you are using Babel: `babel-node` (see repro repo)

**Possible Solution**

Maybe configure the `resolve` module with `moduleDirectory: ['.', 'node_modules']`? https://www.npmjs.com/package/resolve#resolveid-opts-cb

I could understand an argument that this is behaving as intended (since `--require` kind of implies... well, `require()` module resolution logic, and seemingly `node --require foo.js bar.js` does not work), but in that case:
- this should perhaps be documented (see note below)
- a note about this should be added to the changelog, since I can imagine this affecting a number of people

**Additional context**

I was going to find a reference in the public docs for babel-node to convinced myself / prove that this isn't documented behavior, but actually it looks like `-r`/`--register` isn't documented _at all_: https://babeljs.io/docs/en/babel-node. Should I open a separate issue/PR for that?

**Comment by nicolo-ribaudo** [comment]
The correct behaviour should be to match exactly what Node.js does, and any difference (except for transpiling obviously) is a bug.

Maybe we should mention in the docs that for Node.js options we reflect the behaviour described in the Node.js docs 🤔

**Comment by serhalp** [comment]
🤷🏼
